name: release
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: actions/create-release@v1
      id: create_release_step
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  upload_artifact:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-linux, x86_64-linux, aarch64-linux, riscv64-linux ]
    runs-on: ubuntu-latest
    needs: create_release
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Build
      run: zig build -Doptimize=ReleaseSmall -Dtarget=${{ matrix.target }}

    - name: Rename
      run: mv zig-out/bin/tree zig-out/bin/tree-${{ matrix.target }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: zig-out/bin/tree-${{ matrix.target }}

    # - name: Upload artifact
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ needs.jobs.create_release.steps.create_release_step.outputs.upload_url }}
    #     asset_path: zig-out/bin/tree
    #     asset_name: tree-${{ matrix.target }}
    #     asset_content_type: application/zip
    #
